Separate jobs for Java and Scala

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -4,7 +4,65 @@ on:
   pull_request:
 
 jobs:
-  compile-and-test:
+  java-compile-and-test:
+    runs-on: ubuntu-18.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          # See https://github.com/actions/checkout/issues/299#issuecomment-677674415
+          ref: ${{ github.event.pull_request.head.sha }}
+
+      - name: Set up JDK 11
+        uses: olafurpg/setup-scala@v10
+        with:
+          java-version: adopt@1.11.0-9
+
+      - uses: actions/cache@v2.1.3
+        with:
+          path: ~/.m2/repository
+          key: maven-repo-${{ hashFiles('**/pom.xml') }}
+          restore-keys: maven-repo-
+
+      - name: copy-identical-files
+        run: |
+          scripts/copy-identical-files.sh
+          git diff --exit-code --color || { echo "[error] Found modified file that was expected to be identical. Run scripts/copy-identical-files.sh"; false; }
+
+      - name: "Shopping analytics service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-analytics-service-java
+
+      - name: "Shopping cart service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java
+
+      - name: "Shopping order service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-order-service-java
+
+      - name: "00 Shopping analytics service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-analytics-service-java
+
+      - name: "00 Shopping cart service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java
+
+      - name: "00 Shopping order service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-order-service-java
+
+      - name: "01 Shopping cart service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/01-shopping-cart-service-java
+
+      - name: "02 Shopping cart service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/02-shopping-cart-service-java
+
+      - name: "03 Shopping cart service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/03-shopping-cart-service-java
+
+      - name: "04 Shopping cart service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/04-shopping-cart-service-java
+
+      - name: "05 Shopping cart service (Java)"
+        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/05-shopping-cart-service-java
+
+  scala-compile-and-test:
     runs-on: ubuntu-18.04
     steps:
       - name: Checkout
@@ -21,12 +79,6 @@ jobs:
       - name: Cache Coursier cache
         uses: coursier/cache-action@v5
 
-      - uses: actions/cache@v2.1.3
-        with:
-          path: ~/.m2/repository
-          key: maven-repo-${{ hashFiles('**/pom.xml') }}
-          restore-keys: maven-repo-
-
       - name: copy-identical-files
         run: |
           scripts/copy-identical-files.sh
@@ -34,58 +86,36 @@ jobs:
 
       - name: "Shopping analytics service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-analytics-service-scala
-      - name: "Shopping analytics service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-analytics-service-java
 
       - name: "Shopping cart service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-scala
-      - name: "Shopping cart service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java
 
       - name: "Shopping order service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-order-service-scala
-      - name: "Shopping order service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/shopping-order-service-java
 
       - name: "00 Shopping analytics service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-analytics-service-scala
-      - name: "00 Shopping analytics service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-analytics-service-java
 
       - name: "00 Shopping cart service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-scala
-      - name: "00 Shopping cart service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java
 
       - name: "00 Shopping order service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-order-service-scala
-      - name: "00 Shopping order service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/00-shopping-order-service-java
 
       - name: "01 Shopping cart service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/01-shopping-cart-service-scala
-      - name: "01 Shopping cart service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/01-shopping-cart-service-java
 
       - name: "02 Shopping cart service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/02-shopping-cart-service-scala
-      - name: "02 Shopping cart service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/02-shopping-cart-service-java
 
       - name: "03 Shopping cart service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/03-shopping-cart-service-scala
-      - name: "03 Shopping cart service (Java)"
-        run: ~/scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/03-shopping-cart-service-java
 
       - name: "04 Shopping cart service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/04-shopping-cart-service-scala
-      - name: "04 Shopping cart service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/04-shopping-cart-service-java
 
       - name: "05 Shopping cart service (Scala)"
         run: scripts/sbt-test.sh docs-source/docs/modules/microservices-tutorial/examples/05-shopping-cart-service-scala
-      - name: "05 Shopping cart service (Java)"
-        run: scripts/mvn-test.sh docs-source/docs/modules/microservices-tutorial/examples/05-shopping-cart-service-java
 
       - name: "Howto example code"
         run: scripts/sbt-test.sh docs-source/docs/modules/how-to/examples/shopping-cart-service-scala
